Added guess the singer game in main index file
nilisha-jais/Musicophilia pull request #184
Opened 2021-06-12 16:22 UTC by shreyansh30saxena

Added Guess the Singer Game in main index file.
Created a div element just like the other games and referenced the link to Guess the Singers folder.

2021-06-12 19:08 UTC, niloysikdar requested changes
Please mention the linked issue @shreyansh30saxena

2021-06-12 19:13 UTC, shreyansh30saxena commented
Issue #165 
Sorry it just slipped out of my mind.

2021-06-13 04:50 UTC, nilisha-jais approved these changes

2021-06-13 04:51 UTC, nilisha-jais commented
Looks good! Thank you :)

2021-06-13 04:52 UTC, merged